### PR TITLE
fix(web): detect secure context for subtle crypto

### LINKED ISSUE #159: Better detection of when `window.crypto.subtle` works (detection of secure context)
The webcrypto API is only available in "secure contexts". We should detect when this isn't the case, make sure we throw `UnsupportedError` with a description error message, and ideally a link to some documentation about "secure contexts".

 * [Webcrypto API docs on mdn](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)
   * This says:
     > Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API#browser_compatibility).

 * [Secure Contexts on mdn](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

We could potentially write up a note about this in the "compatibility notes" section in the `README.md`.

-------------

Also it'd be nice if we had some test cases for this. Those might have to be manual test cases, because `dart test` running in the browser will probably fake a secure context.

### PR DESCRIPTION
**Pull request by HamdaanAliQuatil**
closes #159

### CODE REVIEW

File: lib/src/crypto_subtle.dart [hunk 1]
```diff
@@ -60,12 +63,38 @@ extension type JSWindow(JSObject _) implements JSObject {
 /// https://developer.mozilla.org/en-US/docs/Web/API/Crypto
 extension type JSCrypto(JSObject _) implements JSObject {
   /// https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle
-  external JSSubtleCrypto get subtle;
+  @JS('subtle')
+  external JSSubtleCrypto? get subtleOrNull;
```
Comment (jonasfj) [inline lib/src/crypto_subtle.dart]:
```suggestion
  @JS('subtle')
  external JSSubtleCrypto? get _subtleOrNull;
  
  JSSubtleCrypto get subtle => requireSubtleCrypto();
```

Then we don't need to refactor the rest of the code.

We can even make `_requireSubtleCrypto` a private function, or inline it inside the `subtle` getter.

**Review by jonasfj — APPROVED** [review]
Minor improvement, but let's consider putting the logic into the `subtle` getter

File: lib/src/crypto_subtle.dart (hunk 1 above)
Comment (HamdaanAliQuatil) [reply lib/src/crypto_subtle.dart]: Makes sense. This is a good design. I'll move the logic behind `crypto.subtle` and keep the nullable raw getter private, so callers can keep using `window.crypto.subtle` normally.

**Comment by HamdaanAliQuatil** [comment]
Added targeted coverage for the new `crypto.subtle` error paths.

The getter design stays the same; I extracted the branch selection into a testable helper and added tests for the two negative cases. Coveralls increased by 0.02%.

File: test/crypto_subtle_test.dart [hunk 2]
```diff
@@ -150,9 +194,11 @@ void main() {
   });
 
   group('crypto.subtle', () {
+    final cryptoSubtle = subtle.window.crypto.subtle;
+
     test('generateCryptoKey: success', () async {
       expect(
-        await subtle.window.crypto.subtle
+        await cryptoSubtle
```
Comment (jonasfj) [inline test/crypto_subtle_test.dart]: if we want to make this change, do it in a different PR

**Comment by HamdaanAliQuatil** [comment]
Makes sense. That alias is unrelated cleanup, so I dropped it from this PR and kept this one focused on the secure-context change.

**Review by jonasfj — APPROVED** [review]

File: lib/src/crypto_subtle.dart [hunk 3]
```diff
@@ -60,12 +63,44 @@ extension type JSWindow(JSObject _) implements JSObject {
...
   external JSTypedArray getRandomValues(JSTypedArray array);
 }
 
+const _webCryptoApiDocumentationUrl =
+    'https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API';
+const _secureContextsDocumentationUrl =
+    'https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts';
+
+@visibleForTesting
+JSSubtleCrypto requireSubtleCrypto(
```
Comment (jonasfj) [inline lib/src/crypto_subtle.dart:82]: For the record, I'd be okay not testing this.

Comment (jonasfj) [reply lib/src/crypto_subtle.dart:82]: filed: https://github.com/google/webcrypto.dart/issues/263

I'm sure we have other things like this too.
